[package]
name = "chessers"
version = "0.1.0"
edition = "2021"
description = "Chess bot using a convolutional network on a 6-channel bitboard to predict optimal moves"


[dependencies]
candle-core = "0.4.1"
candle-nn = "0.4.1"
chess = "3.2.0"
chrono = "0.4.35"
rand = "0.8.5"
