[package]
name = "chessers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candle-core = "0.4.1"
candle-nn = "0.4.1"
chess = "3.2.0"
chrono = "0.4.35"
rand = "0.8.5"
